version: '3.8'
name: twitter

services:
  gateway:
    container_name: gateway
    build:
      context: ./backend/dotnet
      dockerfile: gateway/Dockerfile
    ports:
      - 7001:7001
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:7001;http://+:5001
      - ASPNETCORE_HTTPS_PORT=7001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
    volumes:
      - ~/.aspnet/https:/https:ro  
    networks:
      - twitter

  storage:
    container_name: storage
    build:
      context: ./backend/go/services/storage
      dockerfile: Dockerfile
    image: twitter/storage:latest
    env_file:
      - ./backend/go/services/storage/.env.local
    networks:
      - twitter

networks:
  twitter:
    name:  twitter  